# Numpy

In [1]:
import numpy as np

In [2]:
# to create numpy array
myarr =np.array([[1,2,3,32,7]])

In [3]:
myarr

array([[ 1,  2,  3, 32,  7]])

In [4]:
# to create numpy array
myarr =np.array([[1,2,3,32,7]],np.int16)

In [5]:
myarr

array([[ 1,  2,  3, 32,  7]], dtype=int16)

In [6]:
myarr[0,1]

2

In [7]:
myarr[0]

array([ 1,  2,  3, 32,  7], dtype=int16)

In [8]:
# it explain about number of rows and colums
myarr.shape

(1, 5)

In [9]:
myarr.dtype

dtype('int16')

In [10]:
# to change the value of an array
myarr[0,1] = 45

In [11]:
myarr[0,1]

45

In [12]:
myarr[0]

array([ 1, 45,  3, 32,  7], dtype=int16)

**array creation methods in numpy**
1. Conversion from other Python structures (i.e. lists and tuples)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3. Replicating, joining, or mutating existing arrays

4. Reading arrays from disk, either from standard or custom formats

5. Creating arrays from raw bytes through the use of strings or buffers

6. Use of special library functions (e.g., random)

# 1. Conversion from other Python structures (i.e. lists and tuples)

In [13]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.dtype


dtype('int32')

In [16]:
listarray.size


9

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray[0]

array([1, 2, 3])

In [19]:
np.array({32,33,34})

array({32, 33, 34}, dtype=object)

# 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [20]:
zeroes = np.zeros((2,5))

In [21]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeroes.shape

(2, 5)

In [23]:
zeroes.dtype

dtype('float64')

In [24]:
zeroes.size

10

In [25]:
rng = np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
Linspace = np.linspace(1,5,12)

In [28]:
Linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
Linspace = np.linspace(2,5,12)

In [30]:
Linspace

array([2.        , 2.27272727, 2.54545455, 2.81818182, 3.09090909,
       3.36363636, 3.63636364, 3.90909091, 4.18181818, 4.45454545,
       4.72727273, 5.        ])

In [31]:
emp =np.empty((4,6))

In [32]:
emp

array([[4.67296746e-307, 1.69121096e-306, 7.56603882e-307,
        7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 9.45754852e-308,
        1.27946076e-307, 1.05700515e-307, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        2.11389826e-307, 1.11260619e-306, 2.22522596e-306]])

In [33]:
emp_like = np.empty_like(Linspace)

In [34]:
emp_like


array([2.        , 2.27272727, 2.54545455, 2.81818182, 3.09090909,
       3.36363636, 3.63636364, 3.90909091, 4.18181818, 4.45454545,
       4.72727273, 5.        ])

In [35]:
ide = np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
# arr.reshape(3,31)

In [42]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr = arr.reshape(3,33)

In [45]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr.shape

(3, 33)

In [47]:
arr = arr.ravel()

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [49]:
arr.shape

(99,)

In [53]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [54]:
ar = np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar.sum(axis = 0)

array([12, 15, 18])

In [57]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [58]:
# for transpose row convert into colums and colums convert into row
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
ar.flat

In [60]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [62]:
# number of dimension
ar.ndim

2

In [63]:
ar.size

9

In [65]:
# total bytes consume bata ta ha
ar.nbytes

36

# 1D array

In [71]:
one = np.array([1,2,3,43,5,6])

In [72]:
one.argmax() #it is a function it give index of max value

3

In [73]:
one.argmin()

0

In [75]:
one.argsort() # it give index of sorted values

array([0, 1, 2, 4, 5, 3], dtype=int64)

# 2d Array

In [91]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [92]:
ar = np.array(x)

In [93]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [94]:
ar.argmax()

6

In [95]:
ar.argmin()

8

In [96]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [97]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [98]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [99]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [101]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [108]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [111]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [109]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [110]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [112]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [113]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [114]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [115]:
np.square(ar)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [117]:
ar.sum()

29

In [118]:
ar.min()

0

In [119]:
ar.max()

7

In [120]:
ar.mean()

3.2222222222222223

In [121]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [123]:
np.where(ar>5) # it give the posision of values greater than value 5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [124]:
type(np.where(ar>5)) 

tuple

In [126]:
np.count_nonzero(ar) # it count the values which is not a zero

8

In [128]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [129]:
ar[1,2] = 0

In [130]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [133]:
np.not_equal(ar,ar2)

array([[False, False,  True],
       [False,  True,  True],
       [ True, False, False]])

In [134]:
import sys

In [139]:
py_ar = [0,4,55,2]

In [140]:
np_ar = np.array(py_ar)

In [141]:
sys.getsizeof(1) * len(py_ar)

112

In [142]:
np_ar.itemsize * np_ar.size

16

In [144]:
np_ar.tolist() # array ki python list bana dy ga

[0, 4, 55, 2]

# practice of interview question

In [5]:
def extendList(val, list=[]):
    list.append(val)
    return list

list1 = extendList(10)
list2 = extendList(123,[])
list3 = extendList('a')

print ("list1 = %s" % list1)
print ("list2 = %s" % list2)
print ("list3 = %s" % list3)

list1 = [10, 'a']
list2 = [123]
list3 = [10, 'a']


In [8]:
my_list = [i for i in range(1, 10)]

In [9]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]